name: UI Tests

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to use'
        default: 'main'
        required: false
        type: string
      base-url:
        description: 'The AppKit lab url'
        default: 'http://localhost:3000/'
        required: false
        type: string
      wallet-url:
        description: 'The wallet url'
        default: 'https://react-wallet.walletconnect.com/'
        required: false
        type: string
      command:
        description: 'The test command to run'
        default: 'playwright:test'
        required: false
        type: string
      skip-playwright-webserver:
        description: 'Skip setting up a local test server'
        default: false
        required: false
        type: boolean
      secure-site-url:
        description: 'Secure site SDK url'
        default: 'https://secure.walletconnect.org/sdk'
        required: false
        type: string
    secrets:
      NEXT_PUBLIC_PROJECT_ID:
        required: true
      TESTS_NEXTAUTH_SECRET:
        required: false
      TESTS_MAILSAC_API_KEY:
        required: false
      TESTS_SOCIAL_EMAIL:
        required: false
      TESTS_SOCIAL_PASSWORD:
        required: false

jobs:
  ui_tests:
    name: 'Playwright Tests'
    runs-on: [self-hosted, aws-ecs-16cpu-64mem-30m]
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
        shardTotal: [5]
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: reown-com/appkit
          ref: ${{ inputs.branch }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Download laboratory artifact
        uses: actions/download-artifact@v4
        with:
          name: laboratory-package

      - name: Extract laboratory package
        run: mkdir -p apps/laboratory && tar -xzf laboratory.tar.gz -C apps/laboratory

      - name: Install Playwright Browsers
        working-directory: ./apps/laboratory/
        run: pnpm playwright:install

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ inputs.base-url }}
          WALLET_URL: ${{ inputs.wallet-url }}
          NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
          SKIP_PLAYWRIGHT_WEBSERVER: ${{ inputs.skip-playwright-webserver }}
          NEXTAUTH_SECRET: ${{ secrets.TESTS_NEXTAUTH_SECRET }}
          MAILSAC_API_KEY: ${{ secrets.TESTS_MAILSAC_API_KEY }}
          NEXT_PUBLIC_SECURE_SITE_SDK_URL: ${{ inputs.secure-site-url }}
          SOCIAL_TEST_EMAIL: ${{ secrets.TESTS_SOCIAL_EMAIL }}
          SOCIAL_TEST_PASSWORD: ${{ secrets.TESTS_SOCIAL_PASSWORD }}
          CI: true
        working-directory: ./apps/laboratory/
        run: pnpm ${{ inputs.command }} --shard=${{ matrix.shard }}/${{ matrix.shardTotal }}

      - name: Run canary with minimal environment config
        env:
          NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
          CI: true
        working-directory: ./apps/laboratory/
        run: pnpm playwright:test:canary

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ matrix.shard }}
          path: ./apps/laboratory/playwright-report/
          retention-days: 7
